name: 'env mapper'
description: 'set env variables that matches a key (like aws env names) to a corresponding set of named values'
inputs:
  envMapperFile:  
    description: 'the yaml file that has the mappings'
    required: true
    default: ''
  envMapperString:
    description: 'the yaml string that has the mappings'
    required: true
    default: ''
  envMapperKey:
    description: 'the key used to match a corresponding set of named values i.e an aws env name like test'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
